### ISSUE TITLE
Add command line arguments to database script

### ISSUE THREAD

**Issue by blorente** [PRL-PRG/scalafix-rule-workshop#17]
It would be great to have proper command line arguments for the database configuration in the database script, so that the db configuration can bubble up the pipeline, and ultimately be customizable. This will specially be useful if we intend to submit an artifact.

I'm thinking something along the lines of `python push_to_db.py --host 127.0.0.1 --port 3306 --user scala --password scala --database scala`. Once the scripts supports this, adding the fields to the pipeline configuration is trivial.

**Comment by fikovnik** [comment]
Not relevant anymore
