### ISSUE TITLE
Add tests for the basic cases

### ISSUE THREAD

**Issue by fikovnik** [PRL-PRG/scalafix-rule-workshop#2]
It would be very useful to be able to test our assumptions about the output on some of the examples that we have and test manually so far.

While scalafix provides fairly high-level test framework, I do not see it very useful for our purposes. We just need a simple scalatest that processes a scala compilation unit and asserts our expectations.

I guess we have two options:
1. check how we can introduce tests in scalafix
2. move to plain scalameta

The second one looks like a bit more work, but another advantage will be that we could refactor the code so it does not need to be all in one big file. Alternatively, we could fork scalafix and add the rule directly there. This will allow us to split it in smaller units and have dependencies (if we fancy any). It is not pretty though.

**Comment by blorente** [comment]
I don't think our choice of testing tooling should affect the use of scalafix. I do agree that scalafix's testing framework is possibly a bit high-level for us, specially as it focuses on DiffTests. However, I believe that `scalafix-testkit`, where the testing framework is defined, is fairly easily modifiable to allow us to run assertions over the semanticdb index of compilation units. This has the benefits of:

- Not having to touch scalafix itself
- Keeping both tests and rules in the same repo (this one)

Utimately, we could switch to plain scalameta and get similar benefits, but I believe that there would be some reinventing the wheel going on to get our rule to run over every file of the codebases in parallel. I guess it's a matter of weighing that work with the work of adapting scalafix, which we can discuss.

**Comment by fikovnik** [comment]
Good, so can you create a simple scalatest for the example with `m*` calls? What would be great is to have:

```scala

val unit = """
| class A {
|   import ExecutionContext.Implicit.global
|   Future(1)
| }
""".stripMargin

val res = ImplicitRule.run(unit)

assertEquals(res.funs.length, 1)
...
```

**Comment by blorente** [comment]
There are a couple of problems that I found, that I wasn't able to solve:

- The semantic rule requires a RuleCtx to run `fix` on, which what runs by each file. We could create an auxiliary method that would be what `fix` calls, but we would still have that dependency with RuleCtx. Maybe there is a way to create artifical RuleCtx's, but I haven't had the chance to look deep into it. 
- I have not found a way to compile just snippets of code. I can parse and get the syntactic tree with quasiquotes and/or `source` annotations, but building the SemanticDB from outside the compiler seems difficult. If I had more time, I'd look into the [semanticdb plugin](http://scalameta.org/tutorial/#semanticdb-scalac).

Other than that, creating and running custom test suites seems easy.

**Comment by fikovnik** [comment]
This has been covered by https://github.com/PRL-PRG/scalafix-rule-workshop/pull/7
