### ISSUE TITLE
Extend pipeline to capture information about synthetic wrappers

### ISSUE THREAD

**Issue by blorente** [PRL-PRG/scalafix-rule-workshop#25]
Synthetic wrappers are inserted when the compiler performs an implicit conversion or class extension. I propose to extend the pipeline in order to capture information about these synthetics, which will allow us to infer the usage of these patterns.

This extension would require a new csv/db table, which would contain the information of these synthetics. The extraction process is exemplified [in the tests](https://github.com/PRL-PRG/scalafix-rule-workshop/blob/0eb18426a648f7646c027fa9b7f39a5435a62a50/src/test/scala/heuristics/ImplicitClassExtensionTest.scala#L37). Following is a description of where we would fill in that information:

- id -> \<path\>:\<line\>:\<call\>, since we are essentially extracting function applications.
- path, line and col -> Extracted similarly to a `FunApp`, from the synthetic.
- fqn -> Extracted from the synthetic.
- fqfn (fully wualified function name), fqparamlist -> Extracted in the data cleanup phase from the fqn
- type: Extracted from the fqn, since for non-single-variable conversions it's [difficult to find the denotation](https://github.com/PRL-PRG/scalafix-rule-workshop/wiki/Patterns:-Heuristics-and-intuitions#application).

Related issues: #1, #2

**Comment by fikovnik** [comment]
Not relevant anymore
