### ISSUE TITLE
Modify pusher script to update projects with the same version instead of appending

### ISSUE THREAD

**Issue by blorente** [PRL-PRG/scalafix-rule-workshop#26]
Currently, I believe that the pusher script simply appends a project and its related data (params, funs) to the database.

It would be great if it could first query the database on the project in question, and if the project exists (with the same version, maybe) update the information instead, so either overwrite the related entries in the tables or just delete them and push everything again.

This would significantly reduce the friction when finding bugs in any stage of the pipeline.

**Comment by fikovnik** [comment]
Not relevant anymore
