### ISSUE TITLE
Data schema changes

### ISSUE THREAD

**Issue by blorente** [PRL-PRG/scalafix-rule-workshop#34]
The current information extracted from the project has proven not to be enough to implement the heuristics for each pattern. Therefore, a new schema is required. The following schema should be sufficient to match at least implicit conversions, and perhaps the use if type classes. (click on the image to edit)

[![](http://yuml.me/b4e15871.png)](http://yuml.me/edit/b4e15871)

The semantics of each table are:
- **Param:** Stores the information regarding a parameter of a declaration.
  - **listIndex:** Which parameter list a parameter belongs to. -1 for the return type, 0 for type parameters, and 1.. for regular parameter lists.
  - **listPosition:** Which (0-indexed) position the parameter takes in its list. For example, in `implicit def[A](x1: B1, x2: B2)(implicit y: C)D`, x2 has `listIndex: 1, listPosition: 0`.
  - The rest are fairly self-explainatory.

- **Declaration:** Each entry corresponds to the declaration of an `implicit val, var, def, object or class`.
  - (used as id) **fqn:** The fully qualified name of the declaration, so that it can be matched.
  - **signature:** The type signature with the resolved names of the types
  - **kind:** Either `val, var, def, object, class or case class`, with modifiers such as `lazy` when appropriate.
  - **location:** Optional, if we have the position in the source code.
 
- **Insertion:** Each entry corresponds to a code insertion by the compiler. It can represent the insertion of an implicit parameter into a function call, the insertion of a call to an implicit function.
  - (used as id) **location:** Same as above, except it is not optional
  - **fqn:** Same as above, used to match with declaration
  - **code:** In the case of a parameter, source code of the call into which the param is inserted. In the case of an inserted call, the code inserted by the compiler.

- **Link:** A table linking the appearances of implicits to their declarations, with the following constraints.
  - A has 0 or more links to insertions.
  - An insertion has exactly one link to a declaration. In the case of an implicit parameter insertion, the link will point to the instantiation of the value passed. In the case of an implicit function being called, the link will point to the definition of such function.

This new structure will allow us to make queries such as:
 "select entries from insertion where the declaration is has kind def and it only has one non-implicit parameter", which matches the implicit conversion pattern.

**Comment by blorente** [comment]
After further discussion, Filip proposed the following example for testing the robustness of the representation, along with an example output https://gist.github.com/blorente/c51e1e6ab605290778523af04e74dff0

Taking that example output, I propose the following representation of the call sites and declarations: https://gist.github.com/blorente/9bc5dd91704e55970cca0dec2bfe884c

Which would result in something like this for the example: https://gist.github.com/blorente/d576d6cb4f6a68b3468d9e3138473dc1

I'm not sure yet how to get some of the information, but I think it should be possible.

**Comment by fikovnik** [comment]
Done
