### ISSUE TITLE
Cleanup the symbol names from scalameta

### ISSUE THREAD

**Issue by fikovnik** [PRL-PRG/scalafix-rule-workshop#4]
The raw data from scalameta should be cleaned up so it does not include the prefixes such as `_root_` and the `.` suffix. The names should be properly extracted so we get a readable function name, val/var or object name. All this should be done at one place - when the data are being pushed to the database.

**Comment by blorente** [comment]
The new data in the db should be clean. The old data is still there, but I won't delete it until we are sure that the extraction and cleanup works well. Please tell me if there are any cleanup cases left to do.

**Comment by fikovnik** [comment]
This has been covered by https://github.com/PRL-PRG/scalafix-rule-workshop/pull/7
